services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatMiniProgramBundle\Command\:
    resource: '../../Command/'
    public: true
  WechatMiniProgramBundle\Controller\:
    resource: '../../Controller/'
  WechatMiniProgramBundle\Procedure\:
    resource: '../../Procedure/'
  WechatMiniProgramBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramBundle\Service\:
    resource: '../../Service/'
    
  WechatMiniProgramBundle\Service\AdminMenu:
    public: true
    
  WechatMiniProgramBundle\Service\Client:
    public: true
    
  WechatMiniProgramBundle\Service\PathParser:
    public: true
