services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatMiniProgramBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  WechatMiniProgramBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramBundle\Service\:
    resource: '../../Service/'
